Add description for total_forks in INFO STATS
redis/redis-doc pull request #1461
Opened 2020-12-09 05:40 UTC by ShooterIT

Ref redis/redis#8155

2020-12-09 05:48 UTC, ShooterIT commented
Hi @itamarhaber I add description for total_forks, but i‘m not clear the following you said.

> update the history section in commands/info.md

2020-12-09 12:16 UTC, itamarhaber commented on commands/info.md
> +*   `total_forks`: Total number of fork operations since the server starts
```suggestion
*   `total_forks`: Total number of fork operations since the server start
```

2020-12-09 12:17 UTC, itamarhaber requested changes
Thanks @ShooterIT - please disregard my comment about history, it is not applicable for this page :)

2020-12-09 12:37 UTC, itamarhaber approved these changes

2020-12-12 15:46 UTC, itamarhaber approved these changes

2020-12-13 08:01 UTC, oranagra approved these changes

2020-12-13 08:02 UTC, merged