Stream command cleanups
redis/redis-doc pull request #1537
Opened 2021-03-19 11:15 UTC by bjosv

Corrected some minor issues which might help others when going through the descriptions of the stream commands:
- Source code only mentions `pending entries list` which is now used in docs.
- Use of `@examples` and `@return`
- State the different return types for the different forms of `XGROUP`

2021-03-21 16:05 UTC, itamarhaber requested changes
Thanks @bjosv - as the idiom goes, cleanliness is next to godliness, so that's great.

Other than reverting the use of `@examples`, most nitpicks are regarding the new style guide #1485.

2021-03-21 16:05 UTC, itamarhaber commented on commands/xgroup.md
> +consumer groups (0 or 1).
```suggestion
needed.
This form returns an @integer-reply with the number of destroyed consumer groups (0 or 1).
```

2021-03-21 16:05 UTC, itamarhaber commented on commands/xgroup.md
> +that the consumer had before it was deleted.
```suggestion
used.
This form returns an @integer-reply with the number of pending messages that the consumer had before it was deleted.
```

2021-03-21 16:05 UTC, itamarhaber commented on commands/xinfo.md
> +entries, groups, consumers and Pending Entries Lists (PELs). This form is available since Redis 6.0.
```suggestion
entries, groups, consumers and Pending Entries Lists (PELs).
This form is available since Redis 6.0.
```

2021-03-22 08:04 UTC, bjosv commented on commands/xautoclaim.md
> +@examples
Ahh, ok.
Just to make sure; when I tried to figure it out in the redis-io repo I thought `@examples` was just a template for a heading, like Description or History, and that it seemed that `@cli` was the tag that was filtered out to be replaced by an interactive Redis session.
I was also using the acl-xx commands as a reference, but maybe this is more of a formal rule that has not been implemented for all commands yet?

2021-03-22 08:11 UTC, bjosv commented
Thanks for the comments and changes, I seemed to have missed the last rule in the formatting rules..
Just a question regarding the`@examples` tag above.

2021-03-22 12:00 UTC, itamarhaber commented on commands/xautoclaim.md
> +@examples
Sorry, my bad, you are totally right of course. Please disregard this and the other one.

2021-03-22 12:00 UTC, itamarhaber approved these changes
A gazillion thank-yous @bjosv - merging.

2021-03-22 12:01 UTC, merged