[WIP] Update SET documentation for NX and GET
redis/redis-doc pull request #1565
Opened 2021-05-05 11:03 UTC by fabianeichinger

Merge after https://github.com/redis/redis/pull/8906

## WIP
I think it would also make sense to clear up the segment "Return value" as it is currently ambiguous whether `EX`/`NX` or `GET` have priority on what's returned.

2021-05-12 07:01 UTC, yoav-steinberg requested changes
I think you're right, would be good to add a subsection in the `return` section detailing behavior when `GET` is passed.

2021-06-04 10:09 UTC, fabianeichinger commented
@yoav-steinberg I think I'm done here. Would love to see this reviewed.

2021-06-07 13:48 UTC, oranagra approved these changes
LGTM.
@itamarhaber care to take a look?

2021-06-08 07:13 UTC, yoav-steinberg approved these changes
:+1:

2021-06-24 14:05 UTC, merged