Added redli to list of clients
redis/redis-doc pull request #1685
Opened 2021-11-19 15:20 UTC by toote

As described in the title

2021-11-21 14:18 UTC, itamarhaber commented
Hello @toote 

Thanks for making the PR and I, too, think Redli deserves a toot from redis.io.

That said, Redli isn't a programmatically-approachable client such as those on this list. It should be mentioned along redis-cli (and possibly https://github.com/laixintao/iredis & https://github.com/mylxsw/redis-tui as well). We don't quite have such a place yet though. Maybe the topics/rediscli page?

2022-01-19 12:16 UTC, zuiderkwast commented
I think interactive clients can be listed under tools, i.e. "Higher level libraries and tools" on the https://redis.io/clients page. `iredis` is there already. (It's a H1 but there's no link anchor for it. :thinking: )

2022-01-19 12:21 UTC, zuiderkwast requested changes

2022-01-19 12:21 UTC, zuiderkwast commented on clients.json
> +  {
Comma is missing after the previous client. That's why there is a JSON parse error and build failure.

Move this to `tools.json`, then I think we can merge it.

2022-01-19 17:22 UTC, zuiderkwast approved these changes
@itamarhaber I hope you agree this should be merged.

2022-01-19 17:22 UTC, zuiderkwast commented on tools.json
> +    "repository": "https://github.com/IBM-Cloud/redli",
I don't think there is a benefit adding the same URL twice. People would click on both just to find out they point to the same page.

```suggestion
    "repository": "https://github.com/IBM-Cloud/redli",
```

2022-01-20 09:15 UTC, merged