Document 'new' keyevent
redis/redis-doc pull request #1872
Opened 2022-04-13 03:27 UTC by lukepalmer

Document the changes in https://github.com/redis/redis/pull/10512

2022-04-13 08:35 UTC, oranagra approved these changes

2022-04-15 15:54 UTC, banker requested changes

2022-04-15 15:54 UTC, banker commented on docs/manual/keyspace-notifications.md
> +*   `>= 7.0`: New event were added
```suggestion
*   `>= 7.0`: Event type `new` added
```

2022-04-15 15:54 UTC, banker commented on docs/manual/keyspace-notifications.md
> +* Every time a new key is added to the data set a `new` event is generated.
```suggestion
* Every time a new key is added to the data set, a `new` event is generated.
```

2022-04-25 12:02 UTC, merged