fix: setbit return 1
redis/redis-doc pull request #2237
Opened 2022-12-07 02:02 UTC by liuwenzhuang

setbit return the original bit value stored at offset, so `setbit key 10 1` should return 0.

2022-12-28 18:28 UTC, itamarhaber commented on docs/manual/pubsub.md
> +3) (integer) 2
Please revert - this is the wire protocol format, not redis-cli.

2022-12-28 18:28 UTC, itamarhaber commented on docs/manual/pubsub.md
> +3) "Hello"
Same comment

2022-12-28 18:28 UTC, itamarhaber commented on docs/manual/pubsub.md
> +3) (integer) 0
Same comment

2022-12-28 18:29 UTC, itamarhaber requested changes
Hello @liuwenzhuang - thanks for catching that erroneous example.

Please revert all the changes you've made to the examples of Pub/Sub's wire protocol.

2023-01-03 13:04 UTC, zuiderkwast commented
> setbit return the original bit value stored at offset, so `setbit key 10 1` should return 0.

We don't know what was stored in the key before the example command was called. It may be 1.

For the other changes, they are just wrong (as @itamarhaber pointed out) so I think this PR can be closed.

2023-01-03 14:19 UTC, itamarhaber commented
I still think the example is misleading, in the sense that on an empty instance, it should return 0.

2023-01-03 15:08 UTC, zuiderkwast commented
Fair enoguh.

2023-01-04 09:02 UTC, liuwenzhuang commented
> Hello @liuwenzhuang - thanks for catching that erroneous example.
> 
> Please revert all the changes you've made to the examples of Pub/Sub's wire protocol.

Done.

2023-01-04 13:42 UTC, itamarhaber approved these changes

2023-01-04 13:42 UTC, merged