Fix typos in protocol-spec.md
redis/redis-doc pull request #2573
Opened 2023-10-23 15:45 UTC by flpcury

Just a couple of typos I stumbled upon.

2023-10-24 19:52 UTC, dwdougherty commented on docs/reference/protocol-spec.md
> +  Before terminating the connection, Redis unconditionally sends `-DENIED` reply, regardless of whether the client writes to the socket.
```suggestion
  Before terminating the connection, Redis unconditionally sends a `-DENIED` reply, regardless of whether the client writes to the socket.
```

2023-10-24 19:52 UTC, dwdougherty requested changes
Add missing article.

2023-10-25 00:52 UTC, flpcury commented
@dwdougherty I have now added the missing article, thanks for catching that

2023-10-25 13:50 UTC, dwdougherty approved these changes

2023-10-25 14:00 UTC, merged