Add note for building redis with TLS support
redis/redis-doc pull request #2641
Opened 2024-01-07 09:17 UTC by valentinogeron

2024-01-08 09:36 UTC, AlonMagrafta commented
@rrelledge @camdenmoors @kaitlynmichael content wise approved 👍

2024-01-08 14:31 UTC, dwdougherty commented on docs/install/install-redis/install-redis-from-source.md
> +To build with TLS support, you'll need OpenSSL development libraries (e.g. libssl-dev on Debian/Ubuntu) and run:
```suggestion
To build with TLS support, you'll need to install OpenSSL development libraries (e.g., libssl-dev on Debian/Ubuntu) and then run:
```

2024-01-08 14:37 UTC, dwdougherty requested changes
Hope you don't mind just a tiny bit of copy-editing.

2024-01-08 15:09 UTC, dwdougherty approved these changes

2024-01-16 09:50 UTC, AlonMagrafta commented
Thanks @dwdougherty - how do we push it to get merged / published?

2024-01-16 14:33 UTC, merged

2024-01-16 14:34 UTC, dwdougherty commented
Merged.